[env]
# Limit concurrent test threads for better performance
RUST_TEST_THREADS = "4"

[build]
# Enable incremental compilation
incremental = true

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[alias]
it = "test --quiet --features integration_tests"
shim = "build --bin kopi-shim --profile release-shim"
perf = "test --quiet --features perf_tests"
