name: Build and Test on push

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_TEST_THREADS: 1
  RUST_BACKTRACE: full
  SKIP_NETWORK_TESTS: 1

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-2025, macos-15-large ]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run clippy
      run: cargo clippy --all-targets
    
    - name: Build all targets
      run: cargo build --all-targets
    
    - name: Run Unit tests
      run: cargo test --quiet --lib 
    
    - name: Run integration tests
      run: cargo test --quiet --features integration_tests
